### ISSUE TITLE
Vm is not registering in hostpool

### ISSUE THREAD

**Issue by damras** [nnellans/terraform-wvd#2]
Hi, after successfully executing this code, everything works fine only the vm is not getting registered in host pool, even the dsc files are in the vm but vm doesn’t show as registered vm in pool.

can you please help out here ! Thanks @nnellans

**Comment by nnellans** [comment]
I think this goes back to your previous issue that you already closed.  Look on the Session Hosts, check the registry at HKLM\SOFTWARE\Microsoft\RDInfraAgent.  What does it say for token?

I think you need to change the syntax for _azurerm_virtual_desktop_host_pool.wvd_pool1.registration_info[0].token_ back to its original syntax with ${ }

I've also updated the code to remove the dynamic Terraform date functions as that was causing 'inconsistent plan' errors like you saw.  So, please try to run again with the new code.

**Comment by damras** [comment]
Thank you, Now it is working perfectly fine, issue was persistent due to date function as you mentioned. @nnellans Great work with DSC extension !
